/*CREATE TABLE "MSA_CONTROL_MARCAC"
(
   VAL_CONTROL_MARCAC bigint PRIMARY KEY NOT NULL,
   COD_ID_PREVID_SOCIAL varchar(20),
   COD_RELOGIO_EXT_CHAVE varchar(100),
   NUM_DIRECAO_ACES int NOT NULL,
   COD_FUNC_MSA varchar(100),
   COD_ID_FEDER varchar(50) NOT NULL,
   COD_HASH varchar(255),
   LOG_IMPORT_PRODUT tinyint,
   COD_LOTE varchar(100),
   COD_NSR int NOT NULL,
   COD_PIS_MSA varchar(12) NOT NULL,
   VAL_PERF_ACES int,
   DAT_MARCAC_ACES datetime NOT NULL,
   NUM_HORAR_MARCAC_ACES int NOT NULL,
   COD_REP varchar(17) NOT NULL,
   COD_UNID_EXT_CHAVE varchar(100),
   COD_USUAR_EXT_CHAVE varchar(100)
); 

CREATE INDEX IDX_MSA_01 ON MSA_CONTROL_MARCAC ("COD_NSR", "COD_REP", "COD_PIS_MSA", "DAT_MARCAC_ACES"); */


select X6_VAR,X6_TIPO,X6_DESCRIC,X6_DESC1, X6_DESC2, X6_CONTEUD from SX6T10 where X6_VAR IN ('MV_APICLO0','MV_APICLO1','MV_APICLO2')

--update SX6T10 set X6_CONTEUD = 'Teste' where X6_VAR = 'MV_APICLO2'